version: 2.1

orbs:
    node: circleci/node@5.2.0

parameters:
    run-build-supply-service-job:
        type: boolean
        default: true
    run-build-all-server-service-job:
        type: boolean
        default: false

jobs:
    run-build-supply:
        working_directory: ~/KabGo/servers/supply
        executor: node/default
        steps:
            - checkout:
                  path: ~/KabGo
            - node/install-packages:
                  app-dir: ~/KabGo/servers/supply
                  cache-path: node_modules
                  override-ci-command: npm i

            - run: npm run format-fix

            - run: npm run build

            - run: chmod +x ~/KabGo/scripts/deploy.sh

            - add_ssh_keys

            - run: ssh -o StrictHostKeyChecking=no -v root@mtech.id.vn -p 24700 "KabGo/scripts/deploy.sh --service supply"
            # - run: ~/KabGo/scripts/deploy.sh --host mtech.id.vn --uname root --port 24700 --service supply

workflows:
    build_supply_service:
        when: << pipeline.parameters.run-build-supply-service-job >>
        jobs:
            - run-build-supply

    build_all_server_service:
        when: << pipeline.parameters.run-build-all-server-service-job >>
        jobs:
            - run-build-supply
