version: 2.1

orbs:
    node: circleci/node@5.2.0

parameters:
    run-build-supply-service-job:
        type: boolean
        default: false
    run-build-service-2-job:
        type: boolean
        default: false

jobs:
    run-build-supply:
        executor: node/default
        working_directory: ~/KabGo/servers/supply
        steps:
            - checkout:
                  path: ~/KabGo
            - node/install-packages:
                  pkg-manager: npm
            - run:
              command: npm run build

workflows:
    build_supply_service:
        when: << pipeline.parameters.run-build-supply-service-job >>
        jobs:
            - run-build-supply
