version: 2.1

orbs:
    node: circleci/node@5.2.0

parameters:
    run-build-supply-service-job:
        type: boolean
        default: true
    run-build-all-server-service-job:
        type: boolean
        default: false

jobs:
    supply-init-service:
        executor: node/default
        working_directory: ~/KabGo
        steps:
            - checkout

            - node/install-packages:
                  app-dir: ~/KabGo/servers/supply
                  cache-path: node_modules
                  override-ci-command: npm ci

            - run:
                  name: Format & clean code
                  command: |
                      cd servers/supply
                      npm run format-fix

            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    supply-check-lint:
        executor: node/default
        working_directory: ~/KabGo
        steps:
            - attach_workspace:
                  at: .

            - run:
                  name: Check code standard
                  command: |
                      cd servers/supply
                      npm run lint-check

    supply-build-service:
        docker:
            - image: cimg/base:current-22.04
        working_directory: ~/KabGo
        steps:
            - attach_workspace:
                  at: .

            - setup_remote_docker

            - run:
                  name: Build supply service
                  command: |
                      cd docker-compose
                      docker system prune -a -f
                      docker-compose -f docker-compose-prod.yml build

    supply-test-service:
        executor: node/default
        working_directory: ~/KabGo
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Health check supply service
                  command: |
                      cd servers/supply
                      npm run test

    # build-supply-service:
    #     working_directory: ~/KabGo/servers/supply
    #     executor: node/default
    #     steps:
    #         - checkout:
    #               path: ~/KabGo
    #         - node/install-packages:
    #               app-dir: ~/KabGo/servers/supply
    #               cache-path: node_modules
    #               override-ci-command: npm ci

    #         - run: npm run format-fix

    #         - run: npm run build

    #         - add_ssh_keys:
    #               fingerprints:
    #                   - "SHA256:mubRTx/rWnPeI9OSRbwV/ig1rC0LpbYCgNsSqQ6ACPg"

    #         - run: ssh -o StrictHostKeyChecking=no -v root@mtech.id.vn -p 24700 "chmod +x ~/KabGo/scripts/deploy.sh && ~/KabGo/scripts/deploy.sh --service supply-service --service-path servers/supply"

    #         # - run: ~/KabGo/scripts/deploy.sh --host mtech.id.vn --uname root --port 24700 --service supply

workflows:
    build_supply_service:
        when: << pipeline.parameters.run-build-supply-service-job >>
        jobs:
            - supply-init-service
            - supply-check-lint:
                  requires:
                      - supply-init-service
            - supply-build-service:
                  requires:
                      - supply-check-lint

    # build_all_server_service:
    #     when: << pipeline.parameters.run-build-all-server-service-job >>
    #     jobs:
    #         - run-build-supply
