FROM node:alpine

WORKDIR /usr/src/grpc

COPY ./grpc ./

COPY ./grpc/package*.json ../

WORKDIR /usr/src

RUN npm ci

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN rm -rf ./grpc

RUN npm run format-fix

RUN npm run build:prod

EXPOSE 5002

CMD ["npm", "run", "start"]