FROM node:alpine

WORKDIR /usr/src

COPY ./grpc/package.json ./

RUN npm ci

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run format-fix

RUN npm run build:prod

COPY ./grpc ../

EXPOSE 5002

CMD ["npm", "run", "start"]