FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .


WORKDIR /usr/src/grpc

COPY ./grpc ./

COPY ./grpc/package*.json ../


WORKDIR /usr/src

RUN npm ci

RUN sh ./grpc/build.sh

RUN ls ./grpc/proto_pb

RUN cp -r ./grpc ./app


WORKDIR /usr/src/app

RUN npm run format-fix

RUN npm run build:prod


EXPOSE 5002

CMD ["npm", "run", "start"]